services:
  mongo_1:
    image: mongo:8.0.9
    container_name: mongo_1
    command: ["--replSet", "rs", "--bind_ip_all", "--port", "27001"]
    ports:
      - "27001:27001"
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - mongo_1_data:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27001/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongo_2:
    image: mongo:8.0.9
    container_name: mongo_2
    command: ["--replSet", "rs", "--bind_ip_all", "--port", "27002"]
    ports:
      - "27002:27002"
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - mongo_2_data:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27002/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongo_3:
    image: mongo:8.0.9
    container_name: mongo_3
    command: ["--replSet", "rs", "--bind_ip_all", "--port", "27003"]
    ports:
      - "27003:27003"
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - mongo_3_data:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27003/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongo_replicas_init:
    image: mongo:8.0.9
    container_name: mongo_replicas_init
    depends_on:
      mongo_1:
        condition: service_healthy
      mongo_2:
        condition: service_healthy
      mongo_3:
        condition: service_healthy
    networks:
      - mongo-net
    volumes:
      - ./init_replset.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: on-failure

volumes:
  mongo_1_data:
  mongo_2_data:
  mongo_3_data:

networks:
  mongo-net:
    driver: bridge
